name: Stock Price Prediction Pipeline

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
  PYTHON_VERSION: '3.13'

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          ls -la
          pwd

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow yfinance xgboost pandas numpy scikit-learn pytest

      - name: Setup MLflow
        run: |
          mkdir -p mlruns
          echo "MLFLOW_EXPERIMENT_NAME=stock_prediction" >> $GITHUB_ENV

      - name: Train model
        run: |
          python stock_price_prediction_validated.py
        continue-on-error: true

      - name: Make predictions
        if: success()
        run: |
          python predict.py > predictions.txt
        continue-on-error: true

      - name: Archive MLflow runs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-runs
          path: |
            mlruns/
            *.py
            predictions.txt
          retention-days: 90

      - name: Store predictions
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: stock-predictions
          path: predictions.txt
          retention-days: 30

      - name: Report status
        if: always()
        run: |
          echo "Workflow completed. Check artifacts for results."